### PR TITLE
Wrap query form into section

### PR DESCRIPTION
**Pull request by WinstonSung**

### CODE REVIEW

**Comment by AlPha5130** [comment]
This PR modified translation keys, but it's not stated in the PR title. And these should be done within translatewiki.net .

Also I don't think I'm going to implement query user ID in special pages (like that in fandom). Only would implement in API.

**Comment by WinstonSung** [comment]
> Translation key modifications should be done within translatewiki.net .

I'm not sure about it though.

**Comment by AlPha5130** [comment]
I still suggest you to put translation key modification into a separate PR.

**Comment by WinstonSung** [comment]
It seems there's only translation key & message addition, no other moditication and translatewiki bot should able to import them to translatewiki.net ?

**Comment by AlPha5130** [comment]
New translation keys can be recognized.

**Comment by AlPha5130** [comment]
I've already found a differrent approach to add a wrapper without adding form section. Closed.

**Comment by WinstonSung** [comment]
That looks perfect.

Thanks a lot!

**Pull request closed without merging**
